version: '2'
catalog:
  name: "Home Assistant"
  version: "0.50.2"
  description: "Complete Home Automation System"
services:
  mariadb:
    scale: 1
    start_on_create: true
  appdaemon:
    scale: 1
    start_on_create: true
  rtl2mqtt:
    scale: 1
    start_on_create: true
  home-assistant:
    scale: 1
    start_on_create: true
  rabbitmq:
    scale: 1
    start_on_create: true
